$('.HomePage').owlCarousel({
    loop:true,
    margin:10,
    nav:true,
    autoplay:false,
autoplayTimeout:1000,
autoplayHoverPause:false,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:3
        },
        1000:{
            items:5
        }
    }
});

$('.productlist').owlCarousel({
    loop:true,
    margin:10,
    nav:true,
    autoplay:false,
autoplayTimeout:1000,
autoplayHoverPause:false,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:3
        },
        1000:{
            items:3
        }
    }
});
$('.clientsay').owlCarousel({
    loop:true,
    margin:10,
    nav:true,
    autoplay:false,
autoplayTimeout:1000,
autoplayHoverPause:false,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:2
        },
        1000:{
            items:2
        }
    }
});

